#!/bin/bash

# See "Platform" section for details: https://codingcompetitions.withgoogle.com/kickstart/faq

ROOT=$(dirname $1)

javac $ROOT/Solution.java || (echo -e "[TEST FAILED] $ROOT/Solution.java\n" && exit 1)
(diff --color=always -y -EZb $ROOT/.stdout <(java -Xms896m -Xmx896m -Xss64m -XX:+UseSerialGC -cp $ROOT Solution < $ROOT/.stdin) && echo -e "[OK] $ROOT/Solution.java\n") \
  || (echo -e "[TEST FAILED] $ROOT/Solution.java\n" && exit 1)