#!/bin/bash

# See "Platform" section for details: https://codingcompetitions.withgoogle.com/kickstart/faq

ROOT=$(dirname $1)

echo "[Java] $ROOT/Solution.java" 
javac $ROOT/Solution.java
diff --color=always -ys -EZb $ROOT/.stdout <(java -Xms896m -Xmx896m -Xss64m -XX:+UseSerialGC -cp $ROOT Solution < $ROOT/.stdin)